# Generated by Django 3.1.6 on 2022-03-17 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cbvapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='student_model',
            new_name='Student',
        ),
    ]
